### ISSUE TITLE
Empty Nerves app "mix compile" fails

### ISSUE THREAD

**Issue by xphil** [nerves-project/nerves_system#7]
Hi,

I've just tried to create my first Nerves app (installed Nerves just a couple of hours ago, so it's up to date), but "mix compile" failed with the following error:

```
phil@rusty:~/tmp/nerves/hello_world$ mix compile
==> nerves_system
Compiling 14 files (.ex)

== Compilation error on file lib/nerves_system/platforms/br.ex ==
** (CompileError) lib/nerves_system/platforms/br.ex:10: Nerves.Package.__struct__/0 is undefined, cannot expand struct Nerves.Package
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```

It seems that it was broken by the recent commit fbcf8e2913e90007682a6c7330bf4b4615f767be "support for using nerves ~> 0.4.0 with older systems", and in my case the fix was to just remove the following code from deps/qemu_arm/nerves_system/lib/nerves_system/platforms/br.ex:
```
  def config(%Nerves.Package{} = package, dest) do
    :noop
  end
```

I'm using: Erlang/OTP 19, Elixir 1.3.3, on Ubuntu 16.04 64bit.

Here's a full terminal log:
```
phil@rusty:~/tmp/nerves$ mix nerves.new hello_world --target qemu_arm
* creating hello_world/config/config.exs
* creating hello_world/lib/hello_world.ex
* creating hello_world/test/test_helper.exs
* creating hello_world/test/hello_world_test.exs
* creating hello_world/rel/vm.args
* creating hello_world/rel/.gitignore
* creating hello_world/.gitignore
* creating hello_world/mix.exs
* creating hello_world/README.md
phil@rusty:~/tmp/nerves$ 
phil@rusty:~/tmp/nerves$ cd hello_world/
phil@rusty:~/tmp/nerves/hello_world$ mix deps.get
Running dependency resolution
Dependency resolution completed
  bbmustache: 1.0.4
  cf: 0.2.2
  erlware_commons: 0.22.0
  exrm: 1.0.8
  getopt: 0.8.2
  nerves: 0.3.4
  nerves_system: 0.1.7
  nerves_system_br: 0.7.0
  nerves_system_qemu_arm: 0.7.0
  nerves_toolchain: 0.7.1
  nerves_toolchain_arm_unknown_linux_gnueabihf: 0.7.1
  nerves_toolchain_ctng: 0.7.1
  providers: 1.6.0
  relx: 3.22.0
* Getting nerves (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves-0.3.4.tar)
  Using locally cached package
* Getting nerves_system_qemu_arm (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system_qemu_arm-0.7.0.tar)
  Using locally cached package
* Getting nerves_system (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system-0.1.7.tar)
  Using locally cached package
* Getting nerves_system_br (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system_br-0.7.0.tar)
  Using locally cached package
* Getting nerves_toolchain_arm_unknown_linux_gnueabihf (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain_arm_unknown_linux_gnueabihf-0.7.1.tar)
  Using locally cached package
* Getting nerves_toolchain (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain-0.7.1.tar)
  Using locally cached package
* Getting nerves_toolchain_ctng (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain_ctng-0.7.1.tar)
  Using locally cached package
* Getting exrm (Hex package)
  Checking package (https://repo.hex.pm/tarballs/exrm-1.0.8.tar)
  Using locally cached package
* Getting relx (Hex package)
  Checking package (https://repo.hex.pm/tarballs/relx-3.22.0.tar)
  Using locally cached package
* Getting bbmustache (Hex package)
  Checking package (https://repo.hex.pm/tarballs/bbmustache-1.0.4.tar)
  Using locally cached package
* Getting cf (Hex package)
  Checking package (https://repo.hex.pm/tarballs/cf-0.2.2.tar)
  Using locally cached package
* Getting erlware_commons (Hex package)
  Checking package (https://repo.hex.pm/tarballs/erlware_commons-0.22.0.tar)
  Using locally cached package
* Getting getopt (Hex package)
  Checking package (https://repo.hex.pm/tarballs/getopt-0.8.2.tar)
Request failed (:timeout)
  Fetch failed. Using locally cached package
* Getting providers (Hex package)
  Checking package (https://repo.hex.pm/tarballs/providers-1.6.0.tar)
  Using locally cached package
phil@rusty:~/tmp/nerves/hello_world$ 
phil@rusty:~/tmp/nerves/hello_world$ 
phil@rusty:~/tmp/nerves/hello_world$ mix compile
==> nerves_system
Compiling 14 files (.ex)

== Compilation error on file lib/nerves_system/platforms/br.ex ==
** (CompileError) lib/nerves_system/platforms/br.ex:10: Nerves.Package.__struct__/0 is undefined, cannot expand struct Nerves.Package
    (stdlib) lists.erl:1354: :lists.mapfoldl/3

could not compile dependency :nerves_system, "mix compile" failed. You can recompile this dependency with "mix deps.compile nerves_system", update it with "mix deps.update nerves_system" or clean it with "mix deps.clean nerves_system"
phil@rusty:~/tmp/nerves/hello_world$ 
phil@rusty:~/tmp/nerves/hello_world$ vim deps/qemu_arm/nerves_system/lib/nerves_system/platforms/br.ex # Removed piece of code that caused compilation error
phil@rusty:~/tmp/nerves/hello_world$ 
phil@rusty:~/tmp/nerves/hello_world$ mix compile
==> nerves_system
Compiling 14 files (.ex)
Generated nerves_system app
==> nerves_system_br
Generated nerves_system_br app
==> nerves_toolchain_ctng
Compiling 2 files (.ex)
Generated nerves_toolchain_ctng app
==> nerves_toolchain
Compiling 2 files (.ex)
Generated nerves_toolchain app
==> nerves_toolchain_arm_unknown_linux_gnueabihf
Compiling 1 file (.ex)
Generated nerves_toolchain_arm_unknown_linux_gnueabihf app
[nerves_toolchain][compile]
[nerves_toolchain][http] Downloading Toolchain
[nerves_toolchain][http] Toolchain Downloaded
[nerves_toolchain][http] Unpacking Toolchain
==> nerves_system_qemu_arm
Generated nerves_system_qemu_arm app
[nerves_system][compile]
[nerves_system][http] Downloading System
[nerves_system][http] System Downloaded
[nerves_system][http] Unpacking System
===> Compiling cf
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Compiling erlware_commons
===> Compiling bbmustache
===> Compiling getopt
===> Compiling providers
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Compiling relx
==> exrm
Compiling 11 files (.ex)
warning: function beam_imports/1 is unused
  lib/exrm/appups.ex:98

warning: variable v2_file is unused
  lib/exrm/appups.ex:84

Generated exrm app
==> nerves
Compiling 5 files (.ex)
Generated nerves app
==> hello_world
Compiling 1 file (.ex)
Generated hello_world app

```

Let me know if you need more info.

Thanks,
Phil Levchenko

**Comment by pdilyard** [comment]
Yep, I got the same problem as well. It seems that no versions of the `:nerves` hex package have ever contained a definition of `Nerves.Package`. There are actually a few files on the `nerves` github repo that are not included in the hex package.

Anyone else that has this problem can fix it temporarily by adding the following to their `mix.exs` and re-fetching deps:
```elixir
{:nerves_system, "0.1.6", override: true}
```

**Comment by mobileoverlord** [comment]
Whoops, Sorry guys. I've been staging things for backwards compat for the next version and it looks like I broke things. I'll push a fix

**Comment by mobileoverlord** [comment]
@xphil @pdilyard you should be able to pull in nerves_system 0.1.8 and things should work

**Comment by xphil** [comment]
@mobileoverlord Everything works now, thanks a lot!
